export enum CommandsEnum {

    // send
    CREATE_LOBBY = "CREATE_LOBBY",
    CLOSE_LOBBY = "CLOSE_LOBBY",
    CLOSE_MULTIPLAYER = "CLOSE_MULTIPLAYER",
    JOIN_TO_LOBBY = "JOIN_TO_LOBBY",
    READY_TO_START = "READY_TO_START",
    FORCE_START = "FORCE_START",


    // receive
    CREATE_LOBBY_SUCCESS = "CREATE_LOBBY_SUCCESS",
    JOIN_TO_LOBBY_SUCCESS = "JOIN_TO_LOBBY_SUCCESS",
    JOIN_PARTY_MEMBER_SUCCESS = "JOIN_PARTY_MEMBER_SUCCESS",
    LEAVE_PARTY_MEMBER_SUCCESS = "LEAVE_PARTY_MEMBER_SUCCESS",
    CLOSE_LOBBY_SUCCESS = "CLOSE_LOBBY_SUCCESS",

    START_GAME_SUCCESS = "START_GAME_SUCCESS",
}
