export enum EventsEnum {
    START_GAME = "START_GAME",
    END_GAME = "END_GAME",

    START_ROUND = "START_ROUND",
    START_ROUND_AFTER = "START_ROUND_AFTER",
    END_ROUND = "END_ROUND",

    START_TURN = "START_TURN",
    START_TURN_AFTER = "START_TURN_AFTER",
    END_TURN = "END_TURN",

    MAKE_ROAD = "MAKE_ROAD",
    MAKE_ROAD_AFTER = "MAKE_ROAD_AFTER",
}
