export enum EventsEnum {
    INITIALIZE_MAP_AFTER = "INITIALIZE_MAP_AFTER",


    START_GAME = "START_GAME",
    END_GAME = "END_GAME",
    END_GAME_AFTER = "END_GAME_AFTER",

    START_ROUND = "START_ROUND",
    START_ROUND_AFTER = "START_ROUND_AFTER",
    END_ROUND = "END_ROUND",
    END_ROUND_AFTER = "END_ROUND_AFTER",

    START_TURN = "START_TURN",
    START_TURN_AFTER = "START_TURN_AFTER",
    END_TURN = "END_TURN",
    END_TURN_AFTER = "END_TURN_AFTER",

    MAKE_ROAD = "MAKE_ROAD",
    DRAW_ROAD = "DRAW_ROAD",
    MAKE_ROAD_AFTER = "MAKE_ROAD_AFTER",

    CONNECT_ARTIFACT = "CONNECT_ARTIFACT",
    CONNECT_TOWN = "CONNECT_TOWN",
    BONUS_ROAD = "BONUS_ROAD",


    MESSAGE = "MESSAGE",

    CLOSE_GAME = "CLOSE_GAME",
}
